SELECT TRUE,FALSE,NULL;
SELECT 'A' IS NOT NULL, 'A' IS NULL, NULL = NULL, NULL IS NULL;
SELECT 5 IS TRUE, 0 IS FALSE, 10 IS NOT NULL;

SELECT TRUE AND TRUE, TRUE AND FALSE, TRUE AND NULL, NULL AND NULL;
SELECT TRUE OR TRUE, TRUE OR FALSE, TRUE OR NULL, NULL OR NULL;
SELECT TRUE XOR TRUE, TRUE XOR FALSE, TRUE XOR NULL, NULL XOR NULL;
SELECT NOT TRUE, NOT FALSE, NOT NULL;

SELECT TRUE OR FALSE, TRUE || FALSE;
SET SESSION sql_mode=PIPES_AS_CONCAT;
SELECT TRUE OR FALSE, TRUE || FALSE;


