DROP TABLE IF EXISTS exmaple;
CREATE TABLE example (
 i TINYINT UNSIGNED NOT NULL,
 c CHAR(2) NULL
) ENGINE=InnoDB DEFAULT CHARSET latin1;

INSERT INTO example (i) VALUES (0), (-1),(255), (9000);

SHOW WARNINGS;

INSERT INTO example (c) VALUES ('A'),('BB'),('CCC');

SHOW WARNINGS;

SELECT * FROM example;

