DROP TABLE IF EXISTS event_test;
CREATE TABLE event_test(
  id       INT UNSIGNED NOT NULL AUTO_INCREMENT,
  created  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  action   VARCHAR(10) NOT NULL,
  val      VARCHAR(10) NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET latin1;

