USE chapter7;
DROP TABLE IF EXISTS trigger_test;
CREATE TABLE trigger_test (
id   INT UNSIGNED NOT NULL AUTO_INCREMENT,
val  VARCHAR(10) NOT NULL,
PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET latin1;

DROP TABLE IF EXISTS logger;
CREATE TABLE logger (
action      ENUM ('Insert','Update','Delete') NOT NULL,
occured     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
id          INT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET latin1;

